const traducoes = {

  pt: {
    'codigo': 'pt-BR',
    'site.titulo': 'Sarah Andrade | Desenvolvedora em formação',

    'menu.inicio': 'Início',
    'menu.sobre': 'Sobre Mim',
    'menu.habilidades': 'Habilidades',
    'menu.projetos': 'Projetos',
    'menu.interesses': 'Interesses',
    'menu.contato': 'Contato',
    'menu.idioma': 'Mudar idioma',
    'menu.abrir': 'Abrir menu',
    'menu.fechar': 'Fechar menu',
    'tema.ativarClaro': 'Ativar modo claro',
    'tema.ativarEscuro': 'Ativar modo escuro',
    'curriculo': 'Currículo',

    'inicio.cargo': 'Desenvolvedora em formação',
    'inicio.texto': 'Apaixonada por tecnologia, livros e criatividade. Gosto de transformar ideias em projetos e usar a programação para encontrar soluções, aprender coisas novas e dar vida ao que imagino.',
    'inicio.botao': 'Ver projetos',
    'inicio.descer': 'Sobre Mim',

    'sobre.etiqueta': 'Sobre mim',
    'sobre.titulo1': 'Mais do que um código,',
    'sobre.titulo2': 'sou eu.',
    'sobre.texto': 'Gosto de transformar ideias em coisas que podem ser vistas, usadas e compartilhadas. Foi na programação que encontrei uma maneira de unir minha curiosidade pela tecnologia com meu lado criativo. Além de programar e ser uma grande fã de Rock and Roll, gosto de livros, escrita e desenho, interesses que também fazem parte da forma como penso e crio. Estou construindo meu caminho como desenvolvedora e, a cada projeto, busco aprender algo novo, experimentar ideias diferentes e transformar problemas em soluções através do código.',
    'sobre.botao': 'Saiba mais',

    'hab.etiqueta': 'Habilidades',
    'hab.titulo1': 'Tecnologia é meu',
    'hab.titulo2': 'idioma.',
    'hab.texto': 'Apresentando interesse por tecnologia desde criança, agora estudo e pratico diversas tecnologias, e estou sempre buscando aprender mais. Aqui estão algumas das minhas principais habilidades:',
    'hab.botao': 'Ver projetos',
    'hab.git': 'Git e GitHub',

    'proj.etiqueta': 'Projetos',
    'proj.titulo1': 'Conheça',
    'proj.titulo2': 'meus projetos:',
    'proj.texto': 'Aqui estão alguns de meus projetos e ideias que já coloquei em prática. Ainda em desenvolvimento, mas com o objetivo de treinar minhas habilidades e unir meus interesses com os códigos.',
    'proj.botao': 'Saiba mais',
    'proj.ferramentas': 'Ferramentas mais utilizadas',
    'proj.p1desc': 'O projeto foi criado durante a aula de FrontEnd, com o objetivo de criar um e-commerce do zero e desenvolver não somente a ideia, como um modelo no Figma e então, desenvolver o código a partir desse modelo.',
    'proj.p2desc': 'O site foi pensado e desenvolvido por mim, tenho muito interesse pelo personagem e decidi unir meus dois interesses em um único projeto.',
    'proj.p3nome': 'Em desenvolvimento',
    'proj.p3desc': 'Projeto ainda em desenvolvimento.',

    'int.etiqueta': 'Interesses',
    'int.titulo1': 'Coisas que me tornam',
    'int.titulo2': 'eu mesma.',
    'int.livros': 'Livros',
    'int.desenho': 'Desenho',
    'int.programacao': 'Programação',
    'int.musica': 'Música',
    'int.starwars': 'Star Wars',
    'int.volei': 'Vôlei',
    'int.viagens': 'Viagens',
    'int.filmes': 'Filmes',
    'int.cit1titulo': 'O que me define',
    'int.cit1texto': 'Cada pequeno detalhe e gosto que tenho é aquilo que me torna eu mesma, é o que me faz combinar minha criatividade e habilidade com algo produtivo, algo que pode ser útil para outras pessoas.',
    'int.cit2titulo': 'Por que misturo universos',
    'int.cit2texto': 'Acho sempre interessante misturar coisas que gosto em meus projetos. A Feynman Bookstore surgiu do meu amor por livros e meu interesse pessoal no físico Richard Feynman. Misturar esses universos me motiva a dar o meu melhor em cada desenvolvimento de código.',

    'cont.etiqueta': 'Contato',
    'cont.titulo1': 'Vamos',
    'cont.titulo2': 'conversar?',
    'cont.texto': 'Caso esteja interessado, entre em contato, estou sempre disponível para bate-papos sobre tecnologia e aberta a novas oportunidades e projetos colaborativos.',
    'cont.nome': 'Nome',
    'cont.email': 'E-mail',
    'cont.mensagem': 'Mensagem',
    'cont.enviar': 'Enviar mensagem',

    'form.erroNome': 'Escreva seu nome.',
    'form.erroEmail': 'Escreva um e-mail válido, como nome@exemplo.com.',
    'form.erroMensagem': 'Escreva uma mensagem com pelo menos 10 caracteres.',
    'form.enviando': 'Enviando...',
    'form.sucesso': 'Mensagem enviada! Obrigada pelo contato, responderei em breve.',
    'form.falha': 'Não foi possível enviar agora. Tente de novo ou me chame por e-mail.',
    'form.semInternet': 'Parece que você está sem internet. Confira a conexão e tente de novo.',

    'rodape.direitos': 'Todos os direitos reservados.',
  },

  en: {
    'codigo': 'en',
    'site.titulo': 'Sarah Andrade | Developer in training',

    'menu.inicio': 'Home',
    'menu.sobre': 'About Me',
    'menu.habilidades': 'Skills',
    'menu.projetos': 'Projects',
    'menu.interesses': 'Interests',
    'menu.contato': 'Contact',
    'menu.idioma': 'Change language',
    'menu.abrir': 'Open menu',
    'menu.fechar': 'Close menu',
    'tema.ativarClaro': 'Switch to light mode',
    'tema.ativarEscuro': 'Switch to dark mode',
    'curriculo': 'Resume',

    'inicio.cargo': 'Developer in training',
    'inicio.texto': 'Passionate about technology, books and creativity. I love turning ideas into projects and using programming to find solutions, learn new things and bring what I imagine to life.',
    'inicio.botao': 'See projects',
    'inicio.descer': 'About Me',

    'sobre.etiqueta': 'About me',
    'sobre.titulo1': 'More than code,',
    'sobre.titulo2': "it's me.",
    'sobre.texto': "I love turning ideas into things that can be seen, used and shared. Programming is where I found a way to combine my curiosity about technology with my creative side. Besides coding and being a big Rock and Roll fan, I love books, writing and drawing, interests that are also part of how I think and create. I'm building my path as a developer and, with every project, I try to learn something new, experiment with different ideas and turn problems into solutions through code.",
    'sobre.botao': 'Learn more',

    'hab.etiqueta': 'Skills',
    'hab.titulo1': 'Technology is my',
    'hab.titulo2': 'language.',
    'hab.texto': "Interested in technology since I was a child, I now study and practice a range of technologies, and I'm always looking to learn more. Here are some of my main skills:",
    'hab.botao': 'See projects',
    'hab.git': 'Git and GitHub',

    'proj.etiqueta': 'Projects',
    'proj.titulo1': 'Explore',
    'proj.titulo2': 'my projects:',
    'proj.texto': "Here are some of the projects and ideas I've already put into practice. Still in progress, but built to train my skills and bring my interests together with code.",
    'proj.botao': 'Learn more',
    'proj.ferramentas': 'Most used tools',
    'proj.p1desc': 'Created during my Front-End class, the goal was to build an e-commerce site from scratch: developing not only the idea, but also a Figma design, and then writing the code based on that design.',
    'proj.p2desc': "A site I planned and built myself. I'm a big fan of the character and decided to bring my two interests together in a single project.",
    'proj.p3nome': 'In progress',
    'proj.p3desc': 'Project still in progress.',

    'int.etiqueta': 'Interests',
    'int.titulo1': 'Things that make me',
    'int.titulo2': 'who I am.',
    'int.livros': 'Books',
    'int.desenho': 'Drawing',
    'int.programacao': 'Programming',
    'int.musica': 'Music',
    'int.starwars': 'Star Wars',
    'int.volei': 'Volleyball',
    'int.viagens': 'Travel',
    'int.filmes': 'Movies',
    'int.cit1titulo': 'What defines me',
    'int.cit1texto': "Every little detail and taste I have is what makes me who I am. It's what lets me combine my creativity and skills into something productive, something that can be useful to other people.",
    'int.cit2titulo': 'Why I mix worlds',
    'int.cit2texto': 'I always find it interesting to mix things I love into my projects. Feynman Bookstore came from my love of books and my personal interest in the physicist Richard Feynman. Blending these worlds motivates me to give my best in every piece of code I write.',

    'cont.etiqueta': 'Contact',
    'cont.titulo1': 'Shall we',
    'cont.titulo2': 'talk?',
    'cont.texto': "If you're interested, get in touch! I'm always up for a chat about technology and open to new opportunities and collaborative projects.",
    'cont.nome': 'Name',
    'cont.email': 'Email',
    'cont.mensagem': 'Message',
    'cont.enviar': 'Send message',

    'form.erroNome': 'Please enter your name.',
    'form.erroEmail': 'Please enter a valid email, like name@example.com.',
    'form.erroMensagem': 'Please write a message with at least 10 characters.',
    'form.enviando': 'Sending...',
    'form.sucesso': "Message sent! Thanks for reaching out, I'll reply soon.",
    'form.falha': "The message couldn't be sent right now. Try again or reach me by email.",
    'form.semInternet': "It looks like you're offline. Check your connection and try again.",

    'rodape.direitos': 'All rights reserved.',
  },

  fr: {
    'codigo': 'fr',
    'site.titulo': 'Sarah Andrade | Développeuse en formation',

    'menu.inicio': 'Accueil',
    'menu.sobre': 'À propos',
    'menu.habilidades': 'Compétences',
    'menu.projetos': 'Projets',
    'menu.interesses': 'Intérêts',
    'menu.contato': 'Contact',
    'menu.idioma': 'Changer de langue',
    'menu.abrir': 'Ouvrir le menu',
    'menu.fechar': 'Fermer le menu',
    'tema.ativarClaro': 'Activer le mode clair',
    'tema.ativarEscuro': 'Activer le mode sombre',
    'curriculo': 'CV',

    'inicio.cargo': 'Développeuse en formation',
    'inicio.texto': "Passionnée de technologie, de livres et de créativité. J'aime transformer des idées en projets et utiliser la programmation pour trouver des solutions, apprendre de nouvelles choses et donner vie à ce que j'imagine.",
    'inicio.botao': 'Voir les projets',
    'inicio.descer': 'À propos',

    'sobre.etiqueta': 'À propos de moi',
    'sobre.titulo1': "Plus qu'un code,",
    'sobre.titulo2': "c'est moi.",
    'sobre.texto': "J'aime transformer des idées en choses que l'on peut voir, utiliser et partager. C'est dans la programmation que j'ai trouvé un moyen d'unir ma curiosité pour la technologie et mon côté créatif. En plus de programmer et d'être une grande fan de rock'n'roll, j'aime les livres, l'écriture et le dessin, des intérêts qui font aussi partie de ma façon de penser et de créer. Je construis mon parcours de développeuse et, à chaque projet, je cherche à apprendre quelque chose de nouveau, à expérimenter des idées différentes et à transformer des problèmes en solutions grâce au code.",
    'sobre.botao': 'En savoir plus',

    'hab.etiqueta': 'Compétences',
    'hab.titulo1': 'La technologie est ma',
    'hab.titulo2': 'langue.',
    'hab.texto': "Intéressée par la technologie depuis l'enfance, j'étudie et pratique aujourd'hui de nombreuses technologies, et je cherche toujours à en apprendre davantage. Voici quelques-unes de mes principales compétences :",
    'hab.botao': 'Voir les projets',
    'hab.git': 'Git et GitHub',

    'proj.etiqueta': 'Projets',
    'proj.titulo1': 'Découvrez',
    'proj.titulo2': 'mes projets :',
    'proj.texto': "Voici quelques projets et idées que j'ai déjà mis en pratique. Encore en développement, mais conçus pour entraîner mes compétences et réunir mes intérêts avec le code.",
    'proj.botao': 'En savoir plus',
    'proj.ferramentas': 'Outils les plus utilisés',
    'proj.p1desc': "Ce projet a été créé pendant mon cours de Front-End, avec pour objectif de concevoir un site e-commerce de A à Z : développer non seulement l'idée, mais aussi une maquette sur Figma, puis écrire le code à partir de cette maquette.",
    'proj.p2desc': "Un site que j'ai imaginé et développé moi-même. Ce personnage me passionne et j'ai décidé de réunir mes deux centres d'intérêt dans un seul projet.",
    'proj.p3nome': 'En développement',
    'proj.p3desc': 'Projet encore en développement.',

    'int.etiqueta': 'Intérêts',
    'int.titulo1': 'Ce qui fait de moi',
    'int.titulo2': 'qui je suis.',
    'int.livros': 'Livres',
    'int.desenho': 'Dessin',
    'int.programacao': 'Programmation',
    'int.musica': 'Musique',
    'int.starwars': 'Star Wars',
    'int.volei': 'Volley-ball',
    'int.viagens': 'Voyages',
    'int.filmes': 'Films',
    'int.cit1titulo': 'Ce qui me définit',
    'int.cit1texto': "Chaque petit détail et chaque goût que j'ai font de moi qui je suis. C'est ce qui me permet d'associer ma créativité et mes compétences à quelque chose de productif, quelque chose qui peut être utile aux autres.",
    'int.cit2titulo': 'Pourquoi je mélange les univers',
    'int.cit2texto': "Je trouve toujours intéressant de mêler les choses que j'aime à mes projets. Feynman Bookstore est né de mon amour des livres et de mon intérêt personnel pour le physicien Richard Feynman. Mélanger ces univers me motive à donner le meilleur de moi-même dans chaque ligne de code.",

    'cont.etiqueta': 'Contact',
    'cont.titulo1': 'Et si on',
    'cont.titulo2': 'discutait ?',
    'cont.texto': 'Si vous êtes intéressé, contactez-moi ! Je suis toujours partante pour discuter de technologie et ouverte à de nouvelles opportunités et à des projets collaboratifs.',
    'cont.nome': 'Nom',
    'cont.email': 'E-mail',
    'cont.mensagem': 'Message',
    'cont.enviar': 'Envoyer le message',

    'form.erroNome': 'Écrivez votre nom.',
    'form.erroEmail': 'Écrivez un e-mail valide, comme nom@exemple.com.',
    'form.erroMensagem': "Écrivez un message d'au moins 10 caractères.",
    'form.enviando': 'Envoi en cours...',
    'form.sucesso': 'Message envoyé ! Merci pour votre message, je vous répondrai bientôt.',
    'form.falha': "Impossible d'envoyer le message pour le moment. Réessayez ou contactez-moi par e-mail.",
    'form.semInternet': 'Il semble que vous soyez hors ligne. Vérifiez votre connexion et réessayez.',

    'rodape.direitos': 'Tous droits réservés.',
  },

  es: {
    'codigo': 'es',
    'site.titulo': 'Sarah Andrade | Desarrolladora en formación',

    'menu.inicio': 'Inicio',
    'menu.sobre': 'Sobre Mí',
    'menu.habilidades': 'Habilidades',
    'menu.projetos': 'Proyectos',
    'menu.interesses': 'Intereses',
    'menu.contato': 'Contacto',
    'menu.idioma': 'Cambiar idioma',
    'menu.abrir': 'Abrir menú',
    'menu.fechar': 'Cerrar menú',
    'tema.ativarClaro': 'Activar modo claro',
    'tema.ativarEscuro': 'Activar modo oscuro',
    'curriculo': 'Currículum',

    'inicio.cargo': 'Desarrolladora en formación',
    'inicio.texto': 'Apasionada por la tecnología, los libros y la creatividad. Me gusta transformar ideas en proyectos y usar la programación para encontrar soluciones, aprender cosas nuevas y dar vida a lo que imagino.',
    'inicio.botao': 'Ver proyectos',
    'inicio.descer': 'Sobre Mí',

    'sobre.etiqueta': 'Sobre mí',
    'sobre.titulo1': 'Más que un código,',
    'sobre.titulo2': 'soy yo.',
    'sobre.texto': 'Me gusta transformar ideas en cosas que se pueden ver, usar y compartir. En la programación encontré una manera de unir mi curiosidad por la tecnología con mi lado creativo. Además de programar y ser una gran fan del rock and roll, me gustan los libros, la escritura y el dibujo, intereses que también forman parte de mi manera de pensar y crear. Estoy construyendo mi camino como desarrolladora y, con cada proyecto, busco aprender algo nuevo, experimentar ideas diferentes y transformar problemas en soluciones a través del código.',
    'sobre.botao': 'Saber más',

    'hab.etiqueta': 'Habilidades',
    'hab.titulo1': 'La tecnología es mi',
    'hab.titulo2': 'idioma.',
    'hab.texto': 'Interesada en la tecnología desde niña, ahora estudio y practico diversas tecnologías, y siempre busco aprender más. Estas son algunas de mis principales habilidades:',
    'hab.botao': 'Ver proyectos',
    'hab.git': 'Git y GitHub',

    'proj.etiqueta': 'Proyectos',
    'proj.titulo1': 'Conoce',
    'proj.titulo2': 'mis proyectos:',
    'proj.texto': 'Estos son algunos de mis proyectos e ideas que ya puse en práctica. Todavía en desarrollo, pero con el objetivo de entrenar mis habilidades y unir mis intereses con el código.',
    'proj.botao': 'Saber más',
    'proj.ferramentas': 'Herramientas más utilizadas',
    'proj.p1desc': 'El proyecto fue creado durante la clase de Front-End, con el objetivo de crear un e-commerce desde cero y desarrollar no solo la idea, sino también un diseño en Figma y, después, el código a partir de ese diseño.',
    'proj.p2desc': 'Un sitio pensado y desarrollado por mí. Me interesa mucho el personaje y decidí unir mis dos intereses en un único proyecto.',
    'proj.p3nome': 'En desarrollo',
    'proj.p3desc': 'Proyecto todavía en desarrollo.',

    'int.etiqueta': 'Intereses',
    'int.titulo1': 'Cosas que me hacen',
    'int.titulo2': 'ser yo misma.',
    'int.livros': 'Libros',
    'int.desenho': 'Dibujo',
    'int.programacao': 'Programación',
    'int.musica': 'Música',
    'int.starwars': 'Star Wars',
    'int.volei': 'Vóleibol',
    'int.viagens': 'Viajes',
    'int.filmes': 'Películas',
    'int.cit1titulo': 'Lo que me define',
    'int.cit1texto': 'Cada pequeño detalle y gusto que tengo es lo que me hace ser yo misma. Es lo que me permite combinar mi creatividad y mis habilidades con algo productivo, algo que puede ser útil para otras personas.',
    'int.cit2titulo': 'Por qué mezclo universos',
    'int.cit2texto': 'Siempre me parece interesante mezclar cosas que me gustan en mis proyectos. Feynman Bookstore nació de mi amor por los libros y de mi interés personal por el físico Richard Feynman. Mezclar estos universos me motiva a dar lo mejor de mí en cada desarrollo de código.',

    'cont.etiqueta': 'Contacto',
    'cont.titulo1': '¿Qué tal si',
    'cont.titulo2': 'conversamos?',
    'cont.texto': 'Si te interesa, ponte en contacto. Siempre estoy disponible para charlar sobre tecnología y abierta a nuevas oportunidades y proyectos colaborativos.',
    'cont.nome': 'Nombre',
    'cont.email': 'Correo electrónico',
    'cont.mensagem': 'Mensaje',
    'cont.enviar': 'Enviar mensaje',

    'form.erroNome': 'Escribe tu nombre.',
    'form.erroEmail': 'Escribe un correo válido, como nombre@ejemplo.com.',
    'form.erroMensagem': 'Escribe un mensaje de al menos 10 caracteres.',
    'form.enviando': 'Enviando...',
    'form.sucesso': '¡Mensaje enviado! Gracias por escribir, responderé pronto.',
    'form.falha': 'No se pudo enviar en este momento. Inténtalo de nuevo o escríbeme por correo.',
    'form.semInternet': 'Parece que no tienes conexión a internet. Revísala e inténtalo de nuevo.',

    'rodape.direitos': 'Todos los derechos reservados.',
  },
};